#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(
         description='Extracts cumulative kappa from Phono3py hdf5.')
parser.add_argument('file',
                    help='phono3py kappa-mxxx.hdf5.')
parser.add_argument('-d', '--direction', metavar='direction', default='avg',
                    help='direction for anisotropic data. Accepts a-c/ '
                         'x-z or average/ avg. Default: average.')
parser.add_argument('--mfp', action='store_true',
                    help='use mean free path instead of frequency')
parser.add_argument('-o', '--output', metavar='name', default='tp-cumkappa',
                    help='output filename, sans extension.'
                         'Default: tp-cumkappa.')
parser.add_argument('-t', '--temperature', metavar='temperature', type=float,
                    default=300,
                    help='temperature in K. Default: 300')

args=parser.parse_args()

import numpy as np
import tp

tp.data.save.cumkappa(args.file, mfp=args.mfp, direction=args.direction,
                      temperature=args.temperature, output=args.output)
