#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(
         description='Generated KPOINTS file for VASP with 0-weighted '
                     'KPOINTS.')
parser.add_argument('mesh', nargs=3, type=int,
                    help='weighted k-point mesh.')
parser.add_argument('-z', '--zero', nargs=3, type=int,
                    help='0-weighted k-point mesh. Default: no 0-weighted '
                         'k-points.')
parser.add_argument('-p', '--poscar', default='POSCAR',
                    help='POSCAR path. Default: POSCAR.')
parser.add_argument('-o', '--output', default='KPOINTS',
                    help='output path. Default: KPOINTS.')

args=parser.parse_args()

import tp

tp.setup.vasp.get_kpoints(args.mesh, args.zero, poscar=args.poscar,
                          output=args.output)
