#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(
         description='Generated KPOINTS file for VASP with 0-weighted '
                     'KPOINTS. Accepts either meshes, which are not '
                     'preferred as they may not be the same as VASP '
                     'would choose, or IBZKPT files.')
parser.add_argument('kpoints', nargs='+',
                    help='IBZKPT file path or weighted k-point mesh.')
parser.add_argument('-z', '--zero', nargs='+',
                    help='IBZKPT file path or 0-weighted k-point mesh. '
                         'Default: no 0-weighted k-points.')
parser.add_argument('-p', '--poscar', default='POSCAR',
                    help='POSCAR path. Default: POSCAR.')
parser.add_argument('-o', '--output', default='KPOINTS',
                    help='output path. Default: KPOINTS.')

args=parser.parse_args()

import tp

if len(args.kpoints) == 1:
    args.kpoints = args.kpoints[0]
else:
    args.kpoints = [int(k) for k in args.kpoints]
if args.zero is not None:
    if len(args.zero) == 1:
        args.zero = args.zero[0]
    else:
        args.zero = [int(k) for k in args.zero]
tp.setup.vasp.get_kpoints(args.kpoints, args.zero, poscar=args.poscar,
                          output=args.output)
